# Generated by Django 4.0.6 on 2022-07-19 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('bike_model', models.TextField()),
                ('number_allocation', models.IntegerField()),
                ('date_entry', models.DateTimeField()),
                ('date_output', models.DateTimeField()),
            ],
        ),
    ]
