# Generated by Django 4.0.6 on 2022-07-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default='5262194d-7e4d-4e9b-8d22-987417666c8b', primary_key=True, serialize=False),
        ),
    ]
