# Generated by Django 4.0.6 on 2022-08-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default='35670334-f462-4d14-b024-caa0b6e5a6cf', primary_key=True, serialize=False),
        ),
    ]
