# Generated by Django 4.0.6 on 2022-08-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default='797fbbd2-40fa-461c-9a02-08930a31a090', primary_key=True, serialize=False),
        ),
    ]
