# Generated by Django 4.0.6 on 2022-08-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default='fb832397-fd2a-4f58-8afd-6b3c956cce5a', primary_key=True, serialize=False),
        ),
    ]
