# Generated by Django 4.0.6 on 2022-08-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default='3b2a0913-9fc3-45fd-90ce-b007dee83e4d', primary_key=True, serialize=False),
        ),
    ]
