# Generated by Django 4.0.6 on 2022-08-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default='6016cddc-171d-4925-bcd4-2352223d9f6b', primary_key=True, serialize=False),
        ),
    ]
