# Generated by Django 4.0.6 on 2022-08-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_alter_reservation_bike_model_alter_reservation_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x00000196B89A2170>', primary_key=True, serialize=False),
        ),
    ]
