# Generated by Django 4.0.6 on 2022-08-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default='6a16809e-6fd0-4a4b-a4a0-b0eb93f68fda', primary_key=True, serialize=False),
        ),
    ]
