# Generated by Django 4.0.6 on 2022-08-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0019_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(default='d532999f-4250-4542-b395-09625829c123', primary_key=True, serialize=False),
        ),
    ]
