# Generated by Django 4.0.6 on 2022-08-24 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0024_alter_reservation_date_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_entry',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
