# Generated by Django 4.0.6 on 2022-08-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0027_alter_reservation_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cpf',
        ),
    ]
