# Generated by Django 4.0.6 on 2022-08-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0028_remove_reservation_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cpf',
            field=models.CharField(default='string', max_length=255),
        ),
    ]
